"""Response contract and shared constants — CLAUDE.md Section 8.1.

This module is the single Python source of truth for the API response shape.
Every other module builds toward these models; none may invent parallel field
names. Locked naming rules embodied here:

- ``domain.confidence``          — Logistic Regression predict_proba output.
- ``issue.similarity_score``     — cosine similarity. NEVER called confidence,
                                   probability, or certainty (CLAUDE.md 6.2/8.1).
- ``issue.issue_match_reason``   — Layer A, generated at request time (6.7).
- ``provision_relevance_rationale`` — Layer B, human-curated (6.7).
- ``legal_information_status``   — explicit safe state, never silent omission.

The mandatory disclaimer is attached to every response, no exceptions
(CLAUDE.md Section 10).
"""

from typing import List, Optional

from pydantic import BaseModel, Field

from app.knowledge_base_loader import APPROVED_DOMAINS

# ---------------------------------------------------------------------------
# Shared constants
# ---------------------------------------------------------------------------

DISCLAIMER = (
    "This information is for legal awareness only and does not constitute "
    "legal advice. Please consult a qualified legal professional for advice "
    "specific to your situation."
)

# Citizen-facing display names for the five approved Phase 1 domains
# (CLAUDE.md Section 3.1). The domain ID set itself is canonical in
# knowledge_base_loader.APPROVED_DOMAINS; the guard below keeps this map from
# ever drifting out of sync with it.
DOMAIN_DISPLAY_NAMES = {
    "cyber_fraud": "Cyber Fraud",
    "consumer_issues": "Consumer Issues",
    "traffic_enforcement": "Traffic Enforcement",
    "workplace_wage": "Workplace / Wage",
    "contractual_disputes": "Contractual Disputes",
}
assert set(DOMAIN_DISPLAY_NAMES) == APPROVED_DOMAINS, (
    "DOMAIN_DISPLAY_NAMES is out of sync with APPROVED_DOMAINS"
)

# legal_information_status values are defined in app.legal_intelligence (the
# module that produces them): "provisions_available" |
# "no_verified_provision_available".

# Input bounds mirror TRAINING_DATA_PLAN.md Section 6 (20-2000 chars). The
# Node.js gateway performs the authoritative validation later; the ML service
# still refuses out-of-bounds input rather than analyzing garbage.
SCENARIO_MIN_LENGTH = 20
SCENARIO_MAX_LENGTH = 2000


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------

class AnalyzeRequest(BaseModel):
    """Body of POST /analyze."""

    scenario: str = Field(
        ...,
        min_length=SCENARIO_MIN_LENGTH,
        max_length=SCENARIO_MAX_LENGTH,
        description="Citizen's natural-language scenario text.",
    )
    request_id: Optional[str] = Field(
        default=None,
        description=(
            "UUID generated by the API gateway. Optional here so the ML "
            "service can also be exercised directly; generated if absent."
        ),
    )


# ---------------------------------------------------------------------------
# Response building blocks (CLAUDE.md Section 8.1)
# ---------------------------------------------------------------------------

class DomainAnalysis(BaseModel):
    id: str
    display_name: str
    confidence: float = Field(
        description="Module 1 classification confidence (predict_proba). "
                    "Model confidence, never legal certainty."
    )
    confidence_label: str


class IssueAnalysis(BaseModel):
    # All Optional: with an empty KB (or no issues for the predicted domain)
    # Module 2 legitimately detects nothing — that is a real state, not an error.
    id: Optional[str] = None
    display_name: Optional[str] = None
    similarity_score: Optional[float] = Field(
        default=None,
        description="Cosine similarity vs curated prototypes. Not a "
                    "probability; never rendered as 'confidence'.",
    )
    issue_match_reason: Optional[str] = Field(
        default=None,
        description="Layer A — transparent pipeline reasoning (CLAUDE.md 6.7).",
    )


class Analysis(BaseModel):
    domain: DomainAnalysis
    issue: IssueAnalysis
    scenario_signals: List[str] = []


class OfficialSource(BaseModel):
    name: Optional[str] = None
    url: Optional[str] = None


class LegalProvision(BaseModel):
    act_id: str
    act: str
    section: str
    title: Optional[str] = None
    simplified_explanation: Optional[str] = None
    provision_relevance_rationale: str = Field(
        description="Layer B — human-curated issue-to-provision rationale."
    )
    official_source: OfficialSource


class PortalOut(BaseModel):
    name: str
    official_url: Optional[str] = None
    purpose: str
    priority: str  # immediate | primary | secondary


class AnalyzeResponse(BaseModel):
    success: bool = True
    request_id: str
    analysis: Analysis
    legal_provisions: List[LegalProvision] = []
    legal_information_status: str
    action_steps: List[str] = []
    portals: List[PortalOut] = []
    low_confidence_warning: bool = False
    needs_clarification: bool = False
    clarification_question: Optional[str] = None
    disclaimer: str = DISCLAIMER


class HealthResponse(BaseModel):
    """GET /health — operational transparency, no legal content."""

    status: str
    classifier_mode: str          # "trained" | "mock"
    issue_detector_mode: str      # "active" | "no_prototypes"
    kb_acts: int
    kb_sections: int
    kb_issues: int
    kb_portals: int
